"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

_env_file = os.path.join(BASE_DIR, ".env")
if os.path.exists(_env_file):
    environ.Env.read_env(_env_file)

env = environ.Env()

SECRET_KEY = env("SECRET_KEY")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "mailsync",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "mailsync" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_DB_DIR = env.str("DB_DIR", default=str(BASE_DIR))
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(_DB_DIR) / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# DEFAULT SETTINGS
EMAIL_MAX_AGE = env.int("EMAIL_MAX_AGE", default=1)
EMAIL_MAX_RESULTS = env.int("EMAIL_MAX_RESULTS", default=1000)

# CONFIGURATION KEYS
ACTUAL_BUDGET_PASSWORD_KEY = "actual-budget_password"
ACTUAL_BUDGET_SYNC_ID_KEY = "actual_budget_sync_id"
GMAIL_CONFIG_KEY = "gmail_creds_json"
GMAIL_TOKEN_KEY = "gmail_token_json"

# SCHEDULER CONFIGURATION KEYS
SCHEDULER_DAYTIME_START_KEY = "scheduler_daytime_start_hour"
SCHEDULER_DAYTIME_END_KEY = "scheduler_daytime_end_hour"
SCHEDULER_DAYTIME_INTERVAL_KEY = "scheduler_daytime_interval_minutes"
SCHEDULER_NIGHTTIME_INTERVAL_KEY = "scheduler_nighttime_interval_minutes"

# UNFOLD ADMIN
UNFOLD = {
    "SITE_TITLE": "AB Email Sync",
    "SITE_HEADER": "Email Transaction Admin",
    "SITE_SYMBOL": "sync",
    "SITE_ICON": lambda request: "/static/mailsync/img/email.png",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "type": "image/png",
            "href": lambda request: "/static/mailsync/img/email.png",
        },
    ],
    "SHOW_HISTORY": False,
    "SHOW_VIEW_ON_SITE": False,
    "ENVIRONMENT": "config.admin_env.environment_callback",
    "DASHBOARD_CALLBACK": "mailsync.views.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "System",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Configuration",
                        "icon": "settings",
                        "link": reverse_lazy("admin:mailsync_configuration_changelist"),
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                "title": "Bank Setup",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Bank Accounts",
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:mailsync_bankaccount_changelist"),
                    },
                    {
                        "title": "Email Parsing Rules",
                        "icon": "rule",
                        "link": reverse_lazy(
                            "admin:mailsync_bankmailconfig_changelist"
                        ),
                    },
                ],
            },
            {
                "title": "Administration",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}
