# Generated by Django 5.2 on 2026-06-05 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('actual_budget_account_name', models.CharField(max_length=255)),
                ('actual_budget_payee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_salary_account', models.BooleanField(default=False)),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_tagname', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BankMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('amount_regex', models.CharField(max_length=255)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailsync.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sync_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('bank_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailsync.bankmail')),
            ],
            options={
                'ordering': ['-sync_time'],
            },
        ),
    ]
