# Generated by Django 5.2 on 2026-06-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['bank_name', 'account_number'], 'verbose_name': 'bank account', 'verbose_name_plural': 'bank accounts'},
        ),
        migrations.AlterModelOptions(
            name='bankmailconfig',
            options={'ordering': ['bank_account__bank_name', 'direction', 'from_name'], 'verbose_name': 'email parsing rule', 'verbose_name_plural': 'email parsing rules'},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'ordering': ['label'], 'verbose_name': 'system configuration', 'verbose_name_plural': 'system configuration'},
        ),
        migrations.AlterModelOptions(
            name='synclog',
            options={'ordering': ['-sync_time'], 'verbose_name': 'sync log', 'verbose_name_plural': 'sync logs'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='actual_budget_payee_name',
            field=models.CharField(blank=True, help_text='Leave blank to use the Actual Budget account name as the payee.', max_length=255, null=True),
        ),
    ]
