# Generated by Django 5.2 on 2026-06-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsync', '0002_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='actual_budget_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='actual_budget_payee_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
