# Generated by Django 5.2 on 2026-06-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsync', '0003_bankaccount_actual_budget_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If set, this configuration will be deleted when its parent is deleted or modified.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mailsync.configuration'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
